# Generated by Django 5.1.6 on 2025-07-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
